// Action types

export const reviewTypes = Object.freeze({
    GET_REVIEW_BY_ID_REQUEST: 'GET_REVIEW_BY_ID_REQUEST',
    GET_REVIEW_BY_ID_SUCCESS: 'GET_REVIEW_BY_ID_SUCCESS',
    GET_REVIEW_BY_ID_FAILURE: 'GET_REVIEW_BY_ID_FAILURE'
});
