// Action types

export const reviewTypes = Object.freeze({
    GET_REVIEW_BY_ID_REQUEST: 'GET_REVIEW_BY_ID_REQUEST',
    GET_REVIEW_BY_ID_SUCCESS: 'GET_REVIEW_BY_ID_SUCCESS',
    GET_REVIEW_BY_ID_FAILURE: 'GET_REVIEW_BY_ID_FAILURE'
});

export const courseTypes = Object.freeze({
    GET_COURSE_BY_ID_REQUEST: 'GET_COURSE_BY_ID_REQUEST',
    GET_COURSE_BY_ID_SUCCESS: 'GET_COURSE_BY_ID_SUCCESS',
    GET_COURSE_BY_ID_FAILURE: 'GET_COURSE_BY_ID_FAILURE'
});

export const professorTypes = Object.freeze({
    GET_ALL_PROFESSORS_REQUEST: 'GET_ALL_PROFESSORS_REQUEST',
    GET_ALL_PROFESSORS_SUCCESS: 'GET_ALL_PROFESSORS_SUCCESS',
    GET_ALL_PROFESSORS_FAILURE: 'GET_ALL_PROFESSORS_FAILURE',
});

export const loginTypes = Object.freeze({
    SET_LOGIN_TOKENS: 'SET_LOGIN_TOKENS',
    SET_LOGIN_TOKENS_FAILURE: 'SET_LOGIN_TOKENS_FAILURE',
    SET_PROFILE_INFO: 'SET_PROFILE_INFO',
    CLEAR_PROFILE_INFO: 'CLEAR_PROFILE_INFO'
});
